import {
  ActionType,
  PageContainer,
  ProColumns,
  ProTable,
} from '@ant-design/pro-components';
import React, { useRef, useState } from 'react';
import { TableAction } from '@/components/TableAction';
import { FormDialog } from '@formily/antd-v5';
import EditForm from './components/EditForm';

const TableList: React.FC<unknown> = () => {
  useState<boolean>(false);

  const actionRef = useRef<ActionType>();
  function editModal(data: any) {
    FormDialog({ title: '编辑', width: 800 }, () => <EditForm />)
      .forOpen((_, next) => {
        next({
          initialValues: { ...data },
        });
      })
      .open()
      .then(async () => {
        actionRef.current?.reload();
      });
  }
  const columns: ProColumns<API.UserInfo>[] = [
    {
      title: '序号',
      dataIndex: 'index',
      valueType: 'indexBorder',
      width: 48,
    },
    {
      title: '编号',
      dataIndex: 'code',
      ellipsis: true,
      hideInSearch: true,
      width: 120,
    },
    {
      title: '名称',
      dataIndex: 'name',
      ellipsis: true,
      width: 150,
    },
    {
      title: '描述',
      dataIndex: 'description',
      hideInSearch: true,
      ellipsis: true,
    },
    {
      title: '操作',
      width: 120,
      fixed: 'right',
      valueType: 'option',
      key: 'option',
      render: (_, record) => (
        <TableAction
          menus={[
            {
              text: '编辑',
              key: 'edit',
              onClick: () => editModal(record),
            },
          ]}
        />
      ),
    },
  ];

  return (
    <PageContainer
      header={{
        title: 'CRUD 示例',
      }}
    >
      <ProTable<any>
        headerTitle="查询表格"
        actionRef={actionRef}
        rowKey="id"
        search={{
          labelWidth: 120,
        }}
        request={() => {
          return new Promise((resolve) => {
            resolve({
              success: true,
              data: [{
                "code": "Product",
                "name": "产品档案",
                "description": "产品档案元数据",
                "parentId": null,
                "parentProperty": null,
                "layout": null,
                "fields": [
                  {
                    "field": "Code",
                    "displayName": "产品编号",
                    "fieldType": 0,
                    "editorType": 11,
                    "required": true,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 0,
                    "formatString": null,
                    "id": "7a3182fb-4ada-4c87-bb1b-d6879c2f148a"
                  },
                  {
                    "field": "Name",
                    "displayName": "产品名称",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": true,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 1,
                    "formatString": null,
                    "id": "ca5a9a75-35fa-467e-bb31-081286d7753f"
                  },
                  {
                    "field": "CategoryId",
                    "displayName": "产品分类",
                    "fieldType": 0,
                    "editorType": 13,
                    "required": true,
                    "readonly": true,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 2,
                    "formatString": null,
                    "id": "649f1db3-b8e1-49d1-92de-9de3a5b6c2a7"
                  },
                  {
                    "field": "Spec",
                    "displayName": "规格型号",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 3,
                    "formatString": null,
                    "id": "da215551-0fdd-422d-be55-03d79cb8a9a6"
                  },
                  {
                    "field": "Series",
                    "displayName": "商品系列",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 4,
                    "formatString": null,
                    "id": "dbe3c8fd-4516-4d65-affa-c4bfda9c2b52"
                  },
                  {
                    "field": "Barcode",
                    "displayName": "条码",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 5,
                    "formatString": null,
                    "id": "3afa42ac-929c-4546-a594-fefdd79ca3e0"
                  },
                  {
                    "field": "CostPrice",
                    "displayName": "参照成本价",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 6,
                    "formatString": null,
                    "id": "b95268ea-45e9-44da-a08d-7c5df7819229"
                  },
                  {
                    "field": "MinStock",
                    "displayName": "安全库存",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 7,
                    "formatString": null,
                    "id": "6d434313-ccbc-46d8-a17a-27503cd258e9"
                  },
                  {
                    "field": "TagPrice",
                    "displayName": "零售价",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 8,
                    "formatString": null,
                    "id": "4a60c232-1f0e-4a51-ab5d-c73694e18a01"
                  },
                  {
                    "field": "Long",
                    "displayName": "长度",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 9,
                    "formatString": null,
                    "id": "1134c47c-3a01-48cc-97c1-8b528466221b"
                  },
                  {
                    "field": "String1",
                    "displayName": "品牌",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 9,
                    "formatString": null,
                    "id": "69c98e36-5158-45b9-b4e4-ac1cab953508"
                  },
                  {
                    "field": "Width",
                    "displayName": "宽",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 10,
                    "formatString": null,
                    "id": "dcf53419-b905-43f9-bc07-27f1db643576"
                  },
                  {
                    "field": "Height",
                    "displayName": "高",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 11,
                    "formatString": null,
                    "id": "abd2925e-fb06-4c5c-b80c-98cf626f34fa"
                  },
                  {
                    "field": "Weight",
                    "displayName": "毛重",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 12,
                    "formatString": null,
                    "id": "1a6cfcff-acbc-4c96-ad8a-6ea320114eb5"
                  },
                  {
                    "field": "NetWeight",
                    "displayName": "净重",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 13,
                    "formatString": null,
                    "id": "584d1b7a-75b2-4eb9-b1ef-265bb5ef0edc"
                  },
                  {
                    "field": "TaxRate",
                    "displayName": "税率",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 14,
                    "formatString": null,
                    "id": "434aec54-2b71-49e2-bc5d-514f16bd3c84"
                  },
                  {
                    "field": "Control",
                    "displayName": "控制",
                    "fieldType": 2,
                    "editorType": 8,
                    "required": true,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": "[{\"value\":\"Sale\",\"label\":\"允许销售\"},{\"value\":\"Produce\",\"label\":\"允许生产\"},{\"value\":\"Outsourcing\",\"label\":\"允许委外\"}]",
                    "componentProps": "{\"mode\":\"multiple\"}",
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 15,
                    "formatString": null,
                    "id": "4ef9ba83-355a-4f2c-b8ff-54fb11a84bb7"
                  },
                  {
                    "field": "Type",
                    "displayName": "物料属性",
                    "fieldType": 2,
                    "editorType": 8,
                    "required": true,
                    "readonly": false,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": "[{\"value\":0,\"label\":\"外购\"},{\"value\":1,\"label\":\"自产\"},{\"value\":2,\"label\":\"虚拟\"},{\"value\":3,\"label\":\"服务\"}]",
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 16,
                    "formatString": null,
                    "id": "9a5c3cce-dba7-43f1-b34b-964bb5be56f0"
                  },
                  {
                    "field": "Description",
                    "displayName": "描述",
                    "fieldType": 0,
                    "editorType": 1,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": "{\"gridSpan\":4}",
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 17,
                    "formatString": null,
                    "id": "f09babf4-b285-4096-8edf-39edabad4bb9"
                  },
                  {
                    "field": "Picture",
                    "displayName": "图片",
                    "fieldType": 0,
                    "editorType": 9,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": "{\"gridSpan\":4}",
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 18,
                    "formatString": null,
                    "id": "0c231c5b-3d95-4118-904e-7cad8d8bdf3d"
                  },
                  {
                    "field": "Status",
                    "displayName": "状态",
                    "fieldType": 2,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": true,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 19,
                    "formatString": null,
                    "id": "a32e999b-e703-4db6-8602-427ae9a2c429"
                  },
                  {
                    "field": "CancelUser",
                    "displayName": "作废人",
                    "fieldType": 4,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "5bfe1466-2160-4ae4-b0bc-98d583f24790"
                  },
                  {
                    "field": "CancelTime",
                    "displayName": "作废时间",
                    "fieldType": 1,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": true,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "5ed6885e-b6aa-43d6-8556-4119be7b5767"
                  },
                  {
                    "field": "ApproveTime",
                    "displayName": "审核时间",
                    "fieldType": 1,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": true,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "65fc5c21-9d38-41f6-a329-04ecc743ab21"
                  },
                  {
                    "field": "CreationTime",
                    "displayName": "创建时间",
                    "fieldType": 1,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": true,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "ad80d4f0-d5be-4a81-8d58-0f72099a7bfa"
                  },
                  {
                    "field": "Creator",
                    "displayName": "创建人",
                    "fieldType": 4,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "c4dd2422-4a3a-4893-8248-6321dc083738"
                  },
                  {
                    "field": "ApproveUser",
                    "displayName": "审核人",
                    "fieldType": 4,
                    "editorType": null,
                    "required": false,
                    "readonly": true,
                    "allowFilter": false,
                    "hidden": false,
                    "showInListTable": true,
                    "editable": false,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": true,
                    "sort": 20,
                    "formatString": null,
                    "id": "f08f3206-20d2-42a0-a5df-901f3badbef9"
                  },
                  {
                    "field": "String2",
                    "displayName": "扩展文本2",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 32,
                    "formatString": null,
                    "id": "c48e15b9-6c8c-4354-af8b-6db06e642861"
                  },
                  {
                    "field": "String3",
                    "displayName": "扩展文本3",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 33,
                    "formatString": null,
                    "id": "3707746a-e653-4ae1-9feb-c181e4e3b386"
                  },
                  {
                    "field": "String4",
                    "displayName": "扩展文本4",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 34,
                    "formatString": null,
                    "id": "970a49dc-1049-4472-b026-4f5c6f5b4311"
                  },
                  {
                    "field": "String5",
                    "displayName": "扩展文本5",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 35,
                    "formatString": null,
                    "id": "0fa8ffc6-af81-426c-816d-cb64bd006f80"
                  },
                  {
                    "field": "String6",
                    "displayName": "扩展文本6",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 36,
                    "formatString": null,
                    "id": "f1555f75-2932-41c4-882f-feb8d2a6ed0a"
                  },
                  {
                    "field": "String7",
                    "displayName": "扩展文本7",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 37,
                    "formatString": null,
                    "id": "bdc3f3b8-f6c5-49ae-8988-72f56e642e0b"
                  },
                  {
                    "field": "String8",
                    "displayName": "扩展文本8",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 38,
                    "formatString": null,
                    "id": "31aa0c1d-57e8-4495-a32f-54c25d863e43"
                  },
                  {
                    "field": "String9",
                    "displayName": "扩展文本9",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 39,
                    "formatString": null,
                    "id": "d629505c-8275-4a03-a9e1-56d3d592dc9d"
                  },
                  {
                    "field": "String10",
                    "displayName": "扩展文本10",
                    "fieldType": 0,
                    "editorType": 0,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 40,
                    "formatString": null,
                    "id": "441f39da-c314-41a6-973c-7ff5b7badbc2"
                  },
                  {
                    "field": "Number1",
                    "displayName": "扩展数字1",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 41,
                    "formatString": null,
                    "id": "c8439dd6-f9d7-4f66-adbc-5c1666e01746"
                  },
                  {
                    "field": "Number2",
                    "displayName": "扩展数字2",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 42,
                    "formatString": null,
                    "id": "d486590b-232f-47e4-94e7-aeade1bde6a7"
                  },
                  {
                    "field": "Number3",
                    "displayName": "扩展数字3",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 43,
                    "formatString": null,
                    "id": "9293135d-08f7-43ea-b42f-45b01cbf4632"
                  },
                  {
                    "field": "Number4",
                    "displayName": "扩展数字4",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 44,
                    "formatString": null,
                    "id": "57e0474c-dc30-46db-80e1-852732f991a0"
                  },
                  {
                    "field": "Number5",
                    "displayName": "扩展数字5",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 45,
                    "formatString": null,
                    "id": "18df675e-76f7-46ee-9b7b-2262d8c986e9"
                  },
                  {
                    "field": "Number6",
                    "displayName": "扩展数字6",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 46,
                    "formatString": null,
                    "id": "511f3607-6d4e-4169-a3dc-fa3ff1cd9684"
                  },
                  {
                    "field": "Number7",
                    "displayName": "扩展数字7",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 47,
                    "formatString": null,
                    "id": "0170be13-30f0-4aea-8dfd-9ba6209382e3"
                  },
                  {
                    "field": "Number8",
                    "displayName": "扩展数字8",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 48,
                    "formatString": null,
                    "id": "ac3af606-1470-469e-b9f1-542673aca47b"
                  },
                  {
                    "field": "Number9",
                    "displayName": "扩展数字9",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 49,
                    "formatString": null,
                    "id": "c1fa912e-743e-44f2-a736-08fe7a9152af"
                  },
                  {
                    "field": "Number10",
                    "displayName": "扩展数字10",
                    "fieldType": 2,
                    "editorType": 2,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 50,
                    "formatString": null,
                    "id": "d9efdaa3-5971-42a1-9234-52d74ad97f69"
                  },
                  {
                    "field": "Date1",
                    "displayName": "扩展日期1",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 51,
                    "formatString": null,
                    "id": "63bf417f-f670-4b5d-8f32-7b8e34582db9"
                  },
                  {
                    "field": "Date2",
                    "displayName": "扩展日期2",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 52,
                    "formatString": null,
                    "id": "48dba568-d8bf-4c4b-af21-cf98d9fb6a1c"
                  },
                  {
                    "field": "Date3",
                    "displayName": "扩展日期3",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 53,
                    "formatString": null,
                    "id": "5a4dea8b-0070-4966-aff4-f0fe899ec91c"
                  },
                  {
                    "field": "Date4",
                    "displayName": "扩展日期4",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 54,
                    "formatString": null,
                    "id": "1cd469ce-5c4c-4433-962f-b069529ff8be"
                  },
                  {
                    "field": "Date5",
                    "displayName": "扩展日期5",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 55,
                    "formatString": null,
                    "id": "fced2fb6-1160-4fd1-92a8-298087fb19ff"
                  },
                  {
                    "field": "Date6",
                    "displayName": "扩展日期6",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 56,
                    "formatString": null,
                    "id": "ce18a987-52a3-448e-bc8b-70a8dd951233"
                  },
                  {
                    "field": "Date7",
                    "displayName": "扩展日期7",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 57,
                    "formatString": null,
                    "id": "56935623-c54e-4b03-adf6-cf69f35634aa"
                  },
                  {
                    "field": "Date8",
                    "displayName": "扩展日期8",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 58,
                    "formatString": null,
                    "id": "948cda13-7849-4a74-a9d7-2e9856645413"
                  },
                  {
                    "field": "Date9",
                    "displayName": "扩展日期9",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 59,
                    "formatString": null,
                    "id": "dab1455e-4b84-417b-b2cb-b3d6de5d8346"
                  },
                  {
                    "field": "Date10",
                    "displayName": "扩展日期10",
                    "fieldType": 1,
                    "editorType": 3,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 60,
                    "formatString": null,
                    "id": "09036045-f7d2-4978-ba6d-649a5ec5db2b"
                  },
                  {
                    "field": "Boolean1",
                    "displayName": "扩展布尔1",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 61,
                    "formatString": null,
                    "id": "97367194-1c26-497a-8220-4372a2225a7c"
                  },
                  {
                    "field": "Boolean2",
                    "displayName": "扩展布尔2",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 62,
                    "formatString": null,
                    "id": "34c24b1b-9002-49b4-a8e6-7886cd7901cf"
                  },
                  {
                    "field": "Boolean3",
                    "displayName": "扩展布尔3",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 63,
                    "formatString": null,
                    "id": "8103737b-1307-43e3-864f-157976cd6b9b"
                  },
                  {
                    "field": "Boolean4",
                    "displayName": "扩展布尔4",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 64,
                    "formatString": null,
                    "id": "59baab3a-c888-4238-b74c-addbb51057c6"
                  },
                  {
                    "field": "Boolean5",
                    "displayName": "扩展布尔5",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 65,
                    "formatString": null,
                    "id": "caf7c1d6-480c-4cde-a662-db94ad62effc"
                  },
                  {
                    "field": "Boolean6",
                    "displayName": "扩展布尔6",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 66,
                    "formatString": null,
                    "id": "dc85a186-8e0a-4c5b-8e89-910d054dc2c9"
                  },
                  {
                    "field": "Boolean7",
                    "displayName": "扩展布尔7",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 67,
                    "formatString": null,
                    "id": "32edbddc-66e3-4512-95a4-d559973cdb66"
                  },
                  {
                    "field": "Boolean8",
                    "displayName": "扩展布尔8",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 68,
                    "formatString": null,
                    "id": "7cad43ae-407a-4cf8-bd1e-2a96b6f6f6dc"
                  },
                  {
                    "field": "Boolean9",
                    "displayName": "扩展布尔9",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 69,
                    "formatString": null,
                    "id": "6dcaad6b-0f87-4df4-94bb-1643ff704460"
                  },
                  {
                    "field": "Boolean10",
                    "displayName": "扩展布尔10",
                    "fieldType": 3,
                    "editorType": 5,
                    "required": false,
                    "readonly": false,
                    "allowFilter": true,
                    "hidden": true,
                    "showInListTable": false,
                    "editable": true,
                    "permission": null,
                    "dataDictionaryCode": null,
                    "options": null,
                    "componentProps": null,
                    "defaultValue": null,
                    "formItemProps": null,
                    "reactions": null,
                    "isRefField": false,
                    "isStatic": false,
                    "sort": 70,
                    "formatString": null,
                    "id": "ce30a311-cac6-4ad1-900b-5fc367978588"
                  }
                ],
                "creator": null,
                "lastModifier": {
                  "tenantId": null,
                  "userName": "admin",
                  "name": "admin",
                  "surname": null,
                  "email": "admin@abp.io",
                  "emailConfirmed": false,
                  "phoneNumber": null,
                  "phoneNumberConfirmed": false,
                  "isActive": true,
                  "lockoutEnabled": true,
                  "qyworkId": null,
                  "dingtalkId": null,
                  "lockoutEnd": null,
                  "onlyMiniApp": false,
                  "totalSignIn": 0,
                  "continuousSignIn": 0,
                  "signInRank": 0,
                  "concurrencyStamp": "f130ff38a6a7465b8c76ffb66471293e",
                  "organizationUnitId": null,
                  "point": 0,
                  "pointRank": 0,
                  "entityVersion": 2,
                  "isDeleted": false,
                  "deleterId": null,
                  "deletionTime": null,
                  "lastModificationTime": "2023-11-25T10:48:17.02973",
                  "lastModifierId": null,
                  "creationTime": "2023-11-25T10:48:16.616511",
                  "creatorId": null,
                  "id": "3a0f168d-8f59-2384-de01-f86c93e76467",
                  "extraProperties": {}
                },
                "lastModificationTime": "2023-11-26T20:56:34.821788",
                "lastModifierId": "3a0f168d-8f59-2384-de01-f86c93e76467",
                "creationTime": "2023-11-25T10:48:17.67835",
                "creatorId": null,
                "id": "3a0f168d-93fc-380f-7ff6-b1ac1ebf6865"
              }]
            })
          })
        }}
        columns={columns}
      />
    </PageContainer>
  );
};

export default TableList;
